<?php
// source: %A%

class Template%a% extends Latte\Template
{

	function render()
	{
%A%
		// prolog Nette\Bridges\CacheLatte\CacheMacro
		Nette\Bridges\CacheLatte\CacheMacro::initRuntime($this, $this->global);

%A%
Noncached content

%A%
		if (Nette\Bridges\CacheLatte\CacheMacro::createCache($netteCacheStorage, '%[\w]+%', $this->global->caches, [$id, 'tags' => 'mytag'])) {
			?>

<h1><?php echo %a% ?></h1>

<?php $this->createTemplate('include.cache.latte', ['localvar' => 11] + $this->params, "include", 'html')->render() ?>

<?php
			$_tmp = array_pop($this->global->caches);
			if (!$_tmp instanceof stdClass) $_tmp->end();
		}

	}

}
