<?php
// source: %A%

class Template%a% extends Latte\Template
{

	function render()
	{
%A%
		// prolog Nette\Bridges\CacheLatte\CacheMacro
		Nette\Bridges\CacheLatte\CacheMacro::initRuntime($this, $this->global);

%A%
		if (Nette\Bridges\CacheLatte\CacheMacro::createCache($netteCacheStorage, '%[\w]+%', $this->global->caches)) {
			?>	<?php echo %a% ?>

<?php
			$_tmp = array_pop($this->global->caches);
			if (!$_tmp instanceof stdClass) $_tmp->end();
		}

	}

}
