<?php
// source: %A%

class Template%a% extends Latte\Template
{

	function render()
	{
%A%
		// prolog Nette\Bridges\CacheLatte\CacheMacro
		Nette\Bridges\CacheLatte\CacheMacro::initRuntime($this);

%A%
Noncached content

%A%
		if (Nette\Bridges\CacheLatte\CacheMacro::createCache($this->global->cacheStorage, '%[\w]+%', $this->global->cacheStack, [$id, 'tags' => 'mytag'])) {
?>

<h1><?php echo %a% ?></h1>

<?php
			/* line 7 */
			$this->createTemplate('include.cache.latte', ['localvar' => 11] + $this->params, "include")->renderToContentType('html');
?>

<?php
			$_tmp = array_pop($this->global->cacheStack);
			if (!$_tmp instanceof stdClass) $_tmp->end();
		}

	}

}
