<?php
// source: %A%

class Template%a% extends Latte\Template
{

	function render()
	{
%A%
// prolog Nette\Bridges\CacheLatte\CacheMacro
Nette\Bridges\CacheLatte\CacheMacro::initRuntime($this, $_g);

// main template
?>
<p>Included file (<?php echo LFilters::escapeHtmlText($localvar) ?>)</p>

<?php if (Nette\Bridges\CacheLatte\CacheMacro::createCache($netteCacheStorage, '%[\w]+%', $_g->caches)) { ?>
	<?php echo LFilters::escapeHtmlText(call_user_func($this->filters->lower, $title)) ?>

<?php $_l->tmp = array_pop($_g->caches); if (!$_l->tmp instanceof stdClass) $_l->tmp->end(); }
	}

}
