<?php
// source: %A%

class Template%a% extends Latte\Runtime\Template
{

	function main()
	{
%A%
		if (Nette\Bridges\CacheLatte\CacheMacro::createCache($this->global->cacheStorage, '%[\w]+%', $this->global->cacheStack)) {
			?>	<?php echo %a% ?>

<?php
			$_tmp = array_pop($this->global->cacheStack);
			if (!$_tmp instanceof stdClass) $_tmp->end();
		}
%A%
	}


	function prepare()
	{
%A%
		Nette\Bridges\CacheLatte\CacheMacro::initRuntime($this);
%A%
	}

}
